#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# setup-test-project.sh — Start local Supabase, seed test data, configure env
#
# Uses Docker via `supabase start` for $0, fully isolated E2E testing.
#
# Prerequisites:
#   - Docker running
#   - Supabase CLI installed (brew install supabase/tap/supabase)
#
# Usage:
#   ./supabase/scripts/setup-test-project.sh          # start + seed
#   ./supabase/scripts/setup-test-project.sh --reset   # stop, start fresh, re-seed
#   ./supabase/scripts/setup-test-project.sh --stop    # just stop
# =============================================================================

cd "$(dirname "$0")/../.."  # project root

ADMIN_EMAIL="admin@test.fieldmapper.org"
ADMIN_PASSWORD="test-admin-password-123"
EDITOR_EMAIL="editor@test.fieldmapper.org"
EDITOR_PASSWORD="test-editor-password-123"

# ----- Handle flags -----
if [ "${1:-}" = "--stop" ]; then
  echo ">> Stopping local Supabase..."
  supabase stop
  echo "   Stopped."
  exit 0
fi

if [ "${1:-}" = "--reset" ]; then
  echo ">> Resetting local Supabase (full wipe)..."
  supabase stop --no-backup 2>/dev/null || true
  rm -f .env.dev.local .env.e2e.local .env.local
fi

# ----- Step 1: Init if needed -----
if [ ! -f supabase/config.toml ]; then
  echo ">> Initializing Supabase project..."
  supabase init --workdir .
  echo "   Done."
fi

# ----- Step 2: Start local Supabase -----
echo ""
echo ">> Starting local Supabase (Docker)..."
supabase start

# Capture the local URLs and keys from JSON output (stable across CLI versions)
echo ""
echo ">> Capturing local credentials..."
STATUS_JSON=$(supabase status --output json 2>/dev/null)

API_URL=$(echo "$STATUS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['API_URL'])")
ANON_KEY=$(echo "$STATUS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['ANON_KEY'])")
SERVICE_KEY=$(echo "$STATUS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['SERVICE_ROLE_KEY'])")
DB_URL=$(echo "$STATUS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['DB_URL'])")

echo "   API URL:     $API_URL"
echo "   Anon key:    ${ANON_KEY:0:20}..."
echo "   Service key:  ${SERVICE_KEY:0:20}..."

# ----- Step 2b: Fix auth.users schema for newer GoTrue -----
echo ""
echo ">> Patching auth.users schema for GoTrue compatibility..."
PGHOST="${PGHOST:-127.0.0.1}"
PGPORT="${PGPORT:-54322}"
PGPASSWORD=postgres psql -h "$PGHOST" -p "$PGPORT" -U supabase_auth_admin -d postgres --quiet <<'AUTHSQL'
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS email_verified boolean DEFAULT false;
AUTHSQL
echo "   Done."

# Restart auth to pick up schema changes
docker restart supabase_auth_birdhouse-mapper > /dev/null 2>&1
sleep 3

# ----- Step 3: Create test users -----
echo ""
echo ">> Creating test users..."

# Use the local auth admin API
curl -s -X POST "${API_URL}/auth/v1/admin/users" \
  -H "apikey: ${SERVICE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_KEY}" \
  -H "Content-Type: application/json" \
  -d "{
    \"email\": \"${ADMIN_EMAIL}\",
    \"password\": \"${ADMIN_PASSWORD}\",
    \"email_confirm\": true
  }" > /dev/null 2>&1 || echo "   (admin user may already exist)"

curl -s -X POST "${API_URL}/auth/v1/admin/users" \
  -H "apikey: ${SERVICE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_KEY}" \
  -H "Content-Type: application/json" \
  -d "{
    \"email\": \"${EDITOR_EMAIL}\",
    \"password\": \"${EDITOR_PASSWORD}\",
    \"email_confirm\": true
  }" > /dev/null 2>&1 || echo "   (editor user may already exist)"

echo "   Created: $ADMIN_EMAIL"
echo "   Created: $EDITOR_EMAIL"

# ----- Step 3b: Backfill public.users from auth.users -----
# The admin API creates auth.users via GoTrue (separate container), which may not
# trigger the handle_new_user function reliably. Ensure public.users rows exist.
echo ""
echo ">> Backfilling public.users..."
PGPASSWORD=postgres psql -h "$PGHOST" -p "$PGPORT" -U postgres -d postgres --quiet <<'BACKFILL'
INSERT INTO users (id, display_name, email, email_verified, full_name)
SELECT id, split_part(email, '@', 1), email, (email_confirmed_at IS NOT NULL), split_part(email, '@', 1)
FROM auth.users
WHERE id NOT IN (SELECT id FROM users)
ON CONFLICT (id) DO NOTHING;
BACKFILL
echo "   Done."

# ----- Step 4: Run seed script -----
echo ""
echo ">> Seeding test data..."

# Extract host/port from DB_URL or use defaults
PGHOST="${PGHOST:-127.0.0.1}"
PGPORT="${PGPORT:-54322}"

PGPASSWORD=postgres psql -h "$PGHOST" -p "$PGPORT" -U postgres -d postgres \
  -f supabase/scripts/seed-test-db.sql \
  --quiet --no-psqlrc 2>&1 | grep -v "^$" || true

echo "   Done."

# ----- Step 5: Write .env.test.local -----
echo ""
echo ">> Writing .env.test.local..."

cat > .env.test.local <<EOF
# Auto-generated by setup-test-project.sh — DO NOT COMMIT
# Local Supabase (Docker)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
TEST_SUPABASE_URL=${API_URL}
TEST_SUPABASE_ANON_KEY=${ANON_KEY}
TEST_SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
TEST_USER_ADMIN_EMAIL=${ADMIN_EMAIL}
TEST_USER_ADMIN_PASSWORD=${ADMIN_PASSWORD}
TEST_USER_EDITOR_EMAIL=${EDITOR_EMAIL}
TEST_USER_EDITOR_PASSWORD=${EDITOR_PASSWORD}
PLAYWRIGHT_BASE_URL=http://localhost:3000
EOF

echo "   Created .env.test.local"

# ----- Step 5b: Write .env.dev.local (local Supabase config) -----
echo ""
echo ">> Writing .env.dev.local..."
cat > .env.dev.local <<EOF
# Auto-generated by setup-test-project.sh — DO NOT COMMIT
# Local Supabase (Docker)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
PLATFORM_DOMAIN=localhost
EOF
echo "   Created .env.dev.local"

# ----- Step 5c: Write .env.e2e.local (E2E server config — no PLATFORM_DOMAIN) -----
echo ""
echo ">> Writing .env.e2e.local..."
cat > .env.e2e.local <<EOF
# Auto-generated by setup-test-project.sh — DO NOT COMMIT
# E2E testing: same as .env.dev.local but WITHOUT PLATFORM_DOMAIN
# so tenant resolution uses Signal D (default org fallback), matching CI.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
EOF
echo "   Created .env.e2e.local"

# ----- Summary -----
echo ""
echo "============================================"
echo " Local Test Environment Ready!"
echo "============================================"
echo ""
echo "Supabase:  ${API_URL}"
echo "Admin:     ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}"
echo "Editor:    ${EDITOR_EMAIL} / ${EDITOR_PASSWORD}"
echo ""
echo "Start dev server:"
echo "  npm run dev:local         # local Supabase + platform domain (uses .env.dev.local)"
echo "  npm run dev:e2e           # local Supabase for E2E tests (no PLATFORM_DOMAIN, matches CI)"
echo "  npm run dev:cloud         # cloud Supabase (uses .env.dev.cloud)"
echo ""
echo "Run E2E tests:"
echo "  npm run dev:e2e           # terminal 1: start server"
echo "  npm run test:e2e          # terminal 2: run tests"
echo ""
echo "Other commands:"
echo "  npm run supabase:stop     # Stop Docker containers"
echo "  npm run supabase:reset    # Wipe and re-seed"
echo "  supabase studio           # Open local dashboard at localhost:54323"
