#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# setup-test-project.sh — Start local Supabase, seed test data, configure env
#
# Uses Docker via `supabase start` for $0, fully isolated E2E testing.
#
# Prerequisites:
#   - Docker running
#   - Supabase CLI installed (brew install supabase/tap/supabase)
#
# Usage:
#   ./supabase/scripts/setup-test-project.sh          # start + seed
#   ./supabase/scripts/setup-test-project.sh --reset   # stop, start fresh, re-seed
#   ./supabase/scripts/setup-test-project.sh --stop    # just stop
# =============================================================================

cd "$(dirname "$0")/../.."  # project root

ADMIN_EMAIL="admin@test.fieldmapper.org"
ADMIN_PASSWORD="test-admin-password-123"
EDITOR_EMAIL="editor@test.fieldmapper.org"
EDITOR_PASSWORD="test-editor-password-123"

# ----- Handle flags -----
if [ "${1:-}" = "--stop" ]; then
  echo ">> Stopping local Supabase..."
  supabase stop
  echo "   Stopped."
  exit 0
fi

if [ "${1:-}" = "--reset" ]; then
  echo ">> Resetting local Supabase (full wipe)..."
  supabase stop --no-backup 2>/dev/null || true
fi

# ----- Step 1: Init if needed -----
if [ ! -f supabase/config.toml ]; then
  echo ">> Initializing Supabase project..."
  supabase init --workdir .
  echo "   Done."
fi

# ----- Step 2: Start local Supabase -----
echo ""
echo ">> Starting local Supabase (Docker)..."
supabase start

# Capture the local URLs and keys
echo ""
echo ">> Capturing local credentials..."
STATUS=$(supabase status --output json 2>/dev/null || supabase status)

# Parse from structured output
API_URL=$(supabase status 2>/dev/null | grep "API URL" | awk '{print $NF}')
ANON_KEY=$(supabase status 2>/dev/null | grep "anon key" | awk '{print $NF}')
SERVICE_KEY=$(supabase status 2>/dev/null | grep "service_role key" | awk '{print $NF}')
DB_URL=$(supabase status 2>/dev/null | grep "DB URL" | awk '{print $NF}')

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ]; then
  echo "   Failed to parse supabase status. Trying manual parse..."
  API_URL="http://127.0.0.1:54321"
  ANON_KEY=$(supabase status | grep -i "anon" | sed 's/.*: *//')
  SERVICE_KEY=$(supabase status | grep -i "service_role" | sed 's/.*: *//')
  DB_URL=$(supabase status | grep -i "DB URL" | sed 's/.*: *//')
fi

echo "   API URL:     $API_URL"
echo "   Anon key:    ${ANON_KEY:0:20}..."
echo "   Service key:  ${SERVICE_KEY:0:20}..."

# ----- Step 2b: Fix auth.users schema for newer GoTrue -----
echo ""
echo ">> Patching auth.users schema for GoTrue compatibility..."
PGHOST="${PGHOST:-127.0.0.1}"
PGPORT="${PGPORT:-54322}"
PGPASSWORD=postgres psql -h "$PGHOST" -p "$PGPORT" -U supabase_auth_admin -d postgres --quiet <<'AUTHSQL'
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS email_verified boolean DEFAULT false;
AUTHSQL
echo "   Done."

# Restart auth to pick up schema changes
docker restart supabase_auth_birdhouse-mapper > /dev/null 2>&1
sleep 3

# ----- Step 3: Create test users -----
echo ""
echo ">> Creating test users..."

# Use the local auth admin API
curl -s -X POST "${API_URL}/auth/v1/admin/users" \
  -H "apikey: ${SERVICE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_KEY}" \
  -H "Content-Type: application/json" \
  -d "{
    \"email\": \"${ADMIN_EMAIL}\",
    \"password\": \"${ADMIN_PASSWORD}\",
    \"email_confirm\": true
  }" > /dev/null 2>&1 || echo "   (admin user may already exist)"

curl -s -X POST "${API_URL}/auth/v1/admin/users" \
  -H "apikey: ${SERVICE_KEY}" \
  -H "Authorization: Bearer ${SERVICE_KEY}" \
  -H "Content-Type: application/json" \
  -d "{
    \"email\": \"${EDITOR_EMAIL}\",
    \"password\": \"${EDITOR_PASSWORD}\",
    \"email_confirm\": true
  }" > /dev/null 2>&1 || echo "   (editor user may already exist)"

echo "   Created: $ADMIN_EMAIL"
echo "   Created: $EDITOR_EMAIL"

# ----- Step 4: Run seed script -----
echo ""
echo ">> Seeding test data..."

# Extract host/port from DB_URL or use defaults
PGHOST="${PGHOST:-127.0.0.1}"
PGPORT="${PGPORT:-54322}"

PGPASSWORD=postgres psql -h "$PGHOST" -p "$PGPORT" -U postgres -d postgres \
  -f supabase/scripts/seed-test-db.sql \
  --quiet 2>&1 | grep -v "^$" || {
    echo "   psql failed, trying supabase db execute..."
    supabase db execute --file supabase/scripts/seed-test-db.sql
  }

echo "   Done."

# ----- Step 5: Write .env.test.local -----
echo ""
echo ">> Writing .env.test.local..."

cat > .env.test.local <<EOF
# Auto-generated by setup-test-project.sh — DO NOT COMMIT
# Local Supabase (Docker)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
TEST_SUPABASE_URL=${API_URL}
TEST_SUPABASE_ANON_KEY=${ANON_KEY}
TEST_SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
TEST_USER_ADMIN_EMAIL=${ADMIN_EMAIL}
TEST_USER_ADMIN_PASSWORD=${ADMIN_PASSWORD}
TEST_USER_EDITOR_EMAIL=${EDITOR_EMAIL}
TEST_USER_EDITOR_PASSWORD=${EDITOR_PASSWORD}
PLAYWRIGHT_BASE_URL=http://localhost:3000
EOF

echo "   Created .env.test.local"

# ----- Summary -----
echo ""
echo "============================================"
echo " Local Test Environment Ready!"
echo "============================================"
echo ""
echo "Supabase:  ${API_URL}"
echo "Admin:     ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}"
echo "Editor:    ${EDITOR_EMAIL} / ${EDITOR_PASSWORD}"
echo ""
echo "Run E2E tests:"
echo "  Terminal 1:  source .env.test.local && npm run dev"
echo "  Terminal 2:  source .env.test.local && npm run test:e2e"
echo ""
echo "Other commands:"
echo "  supabase studio           # Open local dashboard at localhost:54323"
echo "  ./supabase/scripts/setup-test-project.sh --reset   # Wipe and re-seed"
echo "  ./supabase/scripts/setup-test-project.sh --stop    # Stop Docker containers"
