import type { SiteConfig } from './types';
import { resolveMapDisplayConfig } from './map-display';

export const DEFAULT_CONFIG: SiteConfig = {
  siteName: 'Field Mapper',
  propertyName: null,
  pwaName: null,
  tagline: 'Map and track points of interest',
  locationName: '',
  propertyId: null,
  mapCenter: { lat: 0, lng: 0, zoom: 2 },
  theme: { preset: 'forest' },
  aboutContent: '# About\n\nDescribe your project here.',
  aboutPageEnabled: true,
  logoUrl: null,
  faviconUrl: null,
  footerText: 'Built with Field Mapper',
  footerLinks: [],
  customMap: null,
  mapStyle: null,
  customNavItems: [],
  setupComplete: false,
  platformDomain: null,
  puckPages: null,
  puckRoot: null,
  puckTemplate: null,
  puckPagesDraft: null,
  puckRootDraft: null,
  puckPageMeta: null,
  mapDisplayConfig: resolveMapDisplayConfig(null, null),
  communicationsEnabled: false,
};
